### ISSUE TITLE
Search result issue with scoping and pagination

### ISSUE THREAD

**Issue by shyamster** [kidpollo/tanker#49] opened 2011-09-20 15:34 UTC
When I try the following for search,

List.published.search_tank ("android", :page => 1, :per_page => 10)

I get 4 records back, but if I do:

List.published.search_tank ("android", :page => 2, :per_page => 10)

I get another four records.  I would have expected all 8 to be returned on page 1.  

List.published.search_tank ("android", :page => 1, :per_page => 20) returns all the 8 records.

**Comment by kidpollo** [comment] 2011-09-22 08:09
I just merged some changes from a pull request done by @adrnai which do some changes to the instatiation logic can you please test your code by using the code from master 

gem 'tanker', :git => 'git://github.com/kidpollo/tanker.git'

**Comment by kidpollo** [comment] 2011-09-23 07:15
It seems I am unable to reproduce this behavior. One good way to debug is looking fo this line

```
results = index.search(query, options)
```

In tanker.rb and throwing a debugger in there.

please reffer to this issue 

https://github.com/kidpollo/tanker/issues/50

**Closed as completed by kidpollo** 2011-09-23 07:15 UTC

**Comment by marcusg** [comment] 2011-09-28 11:34
Now, after getting the pagination to work i run into the same problem with pagination and scopes! Here is what i did:

``` ruby
# it's working without scopes
t = Tour.search_tank "spanien"
t.count
>> 9
t.count
>> 9

# but not with!
t = Tour.reduce_to_coming_scope.search_tank "spanien"
t.count 
>> 2 # this is correct
t.total_entries
>> 9 # this is the wrong, there are only 2

```

so i think total_entries is not counting correct, any ideas?

**Comment by kidpollo** [comment] 2011-09-28 17:26
Hey @marcusg

Using scopes on tanker is a strange feature I added from someone in the community because it leads to all sorts of confusion. 

Named scopes in Rails are no more that filters. A search index does not filter the same way a RBMS filters so what you are getting is accurate. The total entries does match what index tanx matches but out of those 9 entries only 2 match your scope.

I would not like to remove that feature cause it might be useful for other people.

**Comment by marcusg** [comment] 2011-09-28 19:06
hey @kidpollo

okay, so there is no change or an update planned? Then I have to find a way to use like I want :) Thanks for your help man!

**Comment by kidpollo** [comment] 2011-09-28 19:11
I would love to see your input in this issue actually :D

The only update for me would be to put a warning in the readme to be careful of using scopes and Index Tank at the same time. 

If you can find some kind of logic that would make scopes affect the search query in a way that makes sense go for it :P

I would personaly use some kind of fuzzy pagination :P

**Comment by marcusg** [comment] 2011-09-28 19:39
Of course, I'll send a pull request when i found a way to implement this in tanker ;)

**Comment by shyamster** [comment] 2011-09-28 20:15
Sorry I disappeared after posting this. I went on a backpacking trip and had no access to work stuff!  I will play with the latest and see if I can help later today.
